# Set all versions
DORAEMON_BUILD_TYPE ?= UNOFFICIAL

DORAEMON_DATE_YEAR := $(shell date -u +%Y)
DORAEMON_DATE_MONTH := $(shell date -u +%m)
DORAEMON_DATE_DAY := $(shell date -u +%d)
DORAEMON_DATE_HOUR := $(shell date -u +%H)
DORAEMON_DATE_MINUTE := $(shell date -u +%M)
DORAEMON_BUILD_DATE_UTC := $(shell date -d '$(DORAEMON_DATE_YEAR)-$(DORAEMON_DATE_MONTH)-$(DORAEMON_DATE_DAY) $(DORAEMON_DATE_HOUR):$(DORAEMON_DATE_MINUTE) UTC' +%s)
DORAEMON_BUILD_DATE := $(DORAEMON_DATE_YEAR)$(DORAEMON_DATE_MONTH)$(DORAEMON_DATE_DAY)-$(DORAEMON_DATE_HOUR)$(DORAEMON_DATE_MINUTE)

DORAEMON_PLATFORM_VERSION := 10.0

TARGET_PRODUCT_SHORT := $(subst aosp_,,$(DORAEMON_BUILD))

DORAEMON_VERSION := PixelExperience_$(DORAEMON_BUILD)-$(DORAEMON_PLATFORM_VERSION)-$(DORAEMON_BUILD_DATE)-$(DORAEMON_BUILD_TYPE)
DORAEMON_VERSION_PROP := 10
ROM_FINGERPRINT := PixelExperience/$(DORAEMON_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(DORAEMON_BUILD_DATE)

CUSTOM_PROPERTIES := \
    ro.doraemon.version=$(DORAEMON_VERSION_PROP) \
    ro.doraemon.version.display=$(DORAEMON_VERSION) \
    ro.doraemon.build_date=$(DORAEMON_BUILD_DATE) \
    ro.doraemon.build_date_utc=$(DORAEMON_BUILD_DATE_UTC) \
    ro.doraemon.build_type=$(DORAEMON_BUILD_TYPE) \
    ro.doraemon.fingerprint=$(ROM_FINGERPRINT)

ifeq ($(DORAEMON_BUILD_TYPE), OFFICIAL)
PRODUCT_DEFAULT_DEV_CERTIFICATE := vendor/secure/releasekey
endif
